# Created by Jekyll Writer
title: Jashon‘s Blog
author: Ja5h0n
description: ''
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: ''
github_username: ''
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: ''
