# Created by Jekyll Writer
title: JaShon Hu
email: DelphicGeek@gmail.com
description: 逆向菜鸟一枚
baseurl: ''
url: ''
permalink: '/:year/:month/:day/:title/'
twitter_username: ''
github_username: ''
markdown: kramdown
