# Created by Jekyll Writer
title: JaShon Hu
email: DelphicGeek@gmail.com
description: Write an awesome description for your new site here
baseurl: ''
url: ''
permalink: '/:year/:month/:day/:title/'
twitter_username: ''
github_username: ''
markdown: kramdown
